Repository PSITS-UC-MAIN/PSITS-WEB, pull requests merged in 2023-09, with the labels that each got.

#16 Integrate new user model from api to OfiiceManagement frontend
  backend/psits_backend/yarn.lock
  frontend/psits_frontend_officemanagement/src/components/Cards/Profile.jsx
  frontend/psits_frontend_officemanagement/src/components/Cards/TimeLog.jsx
  frontend/psits_frontend_officemanagement/src/components/Utils/Calendar.jsx
  frontend/psits_frontend_officemanagement/src/models/user.js
Labels: enhancement

#26 Office Management Fix
  backend/psits_backend/src/controllers/authController.js
  backend/psits_backend/yarn.lock
  frontend/psits_frontend_officemanagement/src/components/Cards/Profile.jsx
  frontend/psits_frontend_officemanagement/src/components/Modal/TimeLogRequestModal.jsx
  frontend/psits_frontend_officemanagement/src/database/api_service.js
  frontend/psits_frontend_officemanagement/src/utilities/server_utils.js
Labels: enhancement

#28 Added "Public/Uploads" Folder in the Backend
  backend/psits_backend/public/uploads/I AM A FILE
Labels: bugfix

#34 Office Management Enhancement
  frontend/psits_frontend_officemanagement/src/App.css
  frontend/psits_frontend_officemanagement/src/components/Cards/AdminDashboard.jsx
  frontend/psits_frontend_officemanagement/src/components/Cards/Profile.jsx
  frontend/psits_frontend_officemanagement/src/components/Modal/TimeLogRequestModal.jsx
  frontend/psits_frontend_officemanagement/src/components/Utils/Button.jsx
  frontend/psits_frontend_officemanagement/src/components/Utils/calendarstyle.css
  frontend/psits_frontend_officemanagement/src/utilities/server_utils.js
Labels: enhancement

#35 WEB ENCHANCEMENT
  backend/psits_backend/src/controllers/announcementController.js
  backend/psits_backend/src/controllers/merchandiseController.js
  backend/psits_backend/src/middlewares/multerMiddleware.js
  frontend/psits_frontend/package-lock.json
  frontend/psits_frontend/package.json
  frontend/psits_frontend/src/App.tsx
  frontend/psits_frontend/src/api/cart.ts
  frontend/psits_frontend/src/api/merchandise.ts
  frontend/psits_frontend/src/api/order.ts
  frontend/psits_frontend/src/assets/index.ts
  frontend/psits_frontend/src/assets/under-construct.svg
  frontend/psits_frontend/src/components/HamburgerMenu.tsx
  frontend/psits_frontend/src/components/Header.tsx
  frontend/psits_frontend/src/components/ProfileAvatar.tsx
  frontend/psits_frontend/src/components/Sidebar.tsx
  frontend/psits_frontend/src/components/cart/Cart.tsx
  frontend/psits_frontend/src/components/merchandise/MerchandiseCard.tsx
  frontend/psits_frontend/src/components/merchandise/MerchandiseFilter.tsx
  frontend/psits_frontend/src/components/ui/accordion.tsx
  frontend/psits_frontend/src/constants/index.ts
  frontend/psits_frontend/src/pages/Maintenance.tsx
  frontend/psits_frontend/src/pages/Orders.tsx
  frontend/psits_frontend/src/pages/Profile.tsx
  frontend/psits_frontend/src/pages/admin/AdminRoutes.tsx
  frontend/psits_frontend/src/pages/community/Students.tsx
  frontend/psits_frontend/src/pages/index.ts
  frontend/psits_frontend/src/pages/merch/Merchandise.tsx
  frontend/psits_frontend/src/pages/merch/ViewSingleMerchandise.tsx
Labels: enhancement, bugfix

#36 Mobile Updates
  backend/psits_backend/src/controllers/announcementController.js
  frontend/psits_frontend/src/assets/index.ts
  frontend/psits_frontend/src/assets/undraw_empty_cart_co35.svg
  frontend/psits_frontend/src/components/cart/Cart.tsx
  frontend/psits_frontend/src/components/merchandise/MerchandiseCard.tsx
  frontend/psits_frontend/src/components/merchandise/MerchandiseFilter.tsx
  frontend/psits_frontend/src/pages/Orders.tsx
Labels: help wanted

#37 WEB ENCHANCEMENT
  backend/psits_backend/src/controllers/announcementController.js
  backend/psits_backend/src/models/AnnouncementModel.js
  backend/psits_backend/src/routes/announcementRouter.js
  frontend/psits_frontend/src/assets/faculty/Caminade.png
  frontend/psits_frontend/src/assets/faculty/Ybanez.png
  frontend/psits_frontend/src/assets/faculty/amores.png
  frontend/psits_frontend/src/assets/faculty/barral.jpg
  frontend/psits_frontend/src/assets/faculty/basabe.png
  frontend/psits_frontend/src/assets/faculty/bermudez.png
  frontend/psits_frontend/src/assets/faculty/codera.png
  frontend/psits_frontend/src/assets/faculty/durano.png
  frontend/psits_frontend/src/assets/faculty/ferolino.png
  frontend/psits_frontend/src/assets/index.ts
  frontend/psits_frontend/src/components/announcements/AnnoucementCard.tsx
  frontend/psits_frontend/src/components/announcements/Announcement.tsx
  frontend/psits_frontend/src/constants/index.ts
  frontend/psits_frontend/src/pages/community/Developers.tsx
  frontend/psits_frontend/src/pages/community/Faculty.tsx
  frontend/psits_frontend/src/pages/community/Officers.tsx
Labels: enhancement, bugfix
